### ISSUE TITLE
PauseAudio and ResumeAudio are only pausing waveIn

### ISSUE THREAD

**Issue by finebytes** [sipsorcery-org/SIPSorceryMedia.Windows#10]
PauseAudio() and ResumeAudio() are only pausing `_waveInEvent` in WindowsAudioEndPoint.

```
        public Task PauseAudio()
        {
            _isPaused = true;
            _waveInEvent?.StopRecording();
            return Task.CompletedTask;
        }

        public Task ResumeAudio()
        {
            _isPaused = false;
            _waveInEvent?.StartRecording();
            return Task.CompletedTask;
        }
```
What if I want to pause `_waveOutEvent` as well?

does it make sense to do a PR, adding an option for that (that defaults to the old behaviour)? like this:
```

        public Task PauseAudio(bool affectWaveOut = false)
        {
            _isPaused = true;
            _waveInEvent?.StopRecording();
		if(affectWaveOut)
		{
			_waveOutEvent?.Pause();
		}

            return Task.CompletedTask;
        }

        public Task ResumeAudio(bool affectWaveOut = false)
        {
            _isPaused = false;
            _waveInEvent?.StartRecording();
		if(affectWaveOut)
		{
			_waveOutEvent?.Play();
		}
            return Task.CompletedTask;
        }
```

Or am I missing something?

**Comment by fred-peters** [comment]
Hi finebytes, according to my understanding of the project, PauseAudio and ResumeAudio are implmentation of the IAudioSource and not IAudioSink, that's why they should not deal with waveOutEvent., that's the purpose of the IAudioSink interface.
If you need a generic (in/out) PauseAudio, this should be implemented at the VoipMediaSession level.
This is unfortunate that the naming of the IAudioSource methods is generic (PauseAudio and ResumeAudio, it should be renamed to PauseAudioSource and ResumeAudioSource like it is correctly done of the IAudioSink interface which has PauseAudioSink and PauseAudioSource methods)

I don't knwo if your comment is related to the merge request I just issued and which affect this behaviour
