### ISSUE TITLE
only one way communication

### ISSUE THREAD

**Issue by nickveliki** [sipsorcery-org/SIPSorceryMedia.Windows#3]
target framework net472

Depending on the device I am trying to call, I can either only hear what the person on the other side is saying, or only they can hear what I am saying. I am trying to call "regular" telephone numbers (via my AVM Fritz Box as a SIP server). My wife on her Iphone and my colleage on the landline at work can talk to me but not hear me, my brother on his android phone can hear me (sort of) but not talk to me.

**Comment by sipsorcery** [comment]
One-way audio on VoIP calls are caused by NAT. They have been a plague on VoIP since it was first carried on the public Internet. You'll find heaps of information about it, here is a [brief summary](https://www.sipsorcery.com/mainsite/Help/SIPAudio) I wrote many years ago.

There are different things you can do to solve the problem. Bridging  calls through a public VoIP/Media/TURN server is the typical solution. It's also worth noting that the newer WebRTC standard uses ICE to overcome this issue. If the remote party/server you are calling supports ICE/WebRTC you could try that instead.
